import {
  Info,
  Loader,
  FileVideo2,
  CalendarDays,
  Zap,
  Frown,
  AudioLines,
  Coins,
  HandCoins,
  Check,
  ServerCrash,
  MessageSquareQuote,
  Key,
} from "lucide-react";

export const Icons = {
  info: Info,
  spinner: Loader,
  videoSize: FileVideo2,
  date: CalendarDays,
  ready: Zap,
  sadFace: Frown,
  audioLines: AudioLines,
  credits: Coins,
  handCredits: HandCoins,
  check: Check,
  errorProcessingVideo: ServerCrash,
  messageSquareQuote:MessageSquareQuote,
  key: Key,
};
